### ISSUE TITLE
Random selects the same category twice

### ISSUE THREAD

**Issue by Moonianne** [Moonianne/pursuit_jeopardy#5]
Need to address how to avoid having the same category be selected twice on inflation.

**Comment by dhchung317** [comment]
https://github.com/Moonianne/pursuit_jeopardy/blob/fe851129001e4d5db9be5817a2ca5109f52423ac/app/src/main/java/org/pursuit/pursuitjeopardy/repository/QuestionsRepository.java#L62

first argument should be the random variable itself.
or did you catch that
